from enum import Enum


class LicenceType(str, Enum):
    ON_DEMAND_LICENSE = "ON_DEMAND_LICENSE"
    ON_DEMAND_FULL_USE_LICENSE = "ON_DEMAND_FULL_USE_LICENSE"
    CUSTOM_LICENSE = "CUSTOM_LICENSE"


ON_DEMAND_LICENSE = LicenceType.ON_DEMAND_LICENSE
ON_DEMAND_FULL_USE_LICENSE = LicenceType.ON_DEMAND_FULL_USE_LICENSE
CUSTOM_LICENSE = LicenceType.CUSTOM_LICENSE


class LicensePermission(str, Enum):
    LICENSE_PERMISSION_PARTIAL_USE = "PARTIAL_USE"
    LICENSE_PERMISSION_FULL_USE = "FULL_USE"
    LICENSE_PERMISSION_CITATION_REQUIRED = "CITATION_REQUIRED"


LICENSE_PERMISSION_PARTIAL_USE = LicensePermission.LICENSE_PERMISSION_PARTIAL_USE
LICENSE_PERMISSION_FULL_USE = LicensePermission.LICENSE_PERMISSION_FULL_USE
LICENSE_PERMISSION_CITATION_REQUIRED = LicensePermission.LICENSE_PERMISSION_CITATION_REQUIRED
