from enum import Enum


class LicensePermission(str, Enum):
    LICENSE_PERMISSION_PARTIAL_USE = "PARTIAL_USE"
    LICENSE_PERMISSION_FULL_USE = "FULL_USE"
    LICENSE_PERMISSION_CITATION_REQUIRED = "CITATION_REQUIRED"


LICENSE_PERMISSION_PARTIAL_USE = LicensePermission.LICENSE_PERMISSION_PARTIAL_USE
LICENSE_PERMISSION_FULL_USE = LicensePermission.LICENSE_PERMISSION_FULL_USE
LICENSE_PERMISSION_CITATION_REQUIRED = LicensePermission.LICENSE_PERMISSION_CITATION_REQUIRED
