from enum import Enum


class LicenseType(str, Enum):
    ON_DEMAND_LICENSE = "ON_DEMAND_LICENSE"
    ON_DEMAND_FULL_USE_LICENSE = "ON_DEMAND_FULL_USE_LICENSE"
    CUSTOM_LICENSE = "CUSTOM_LICENSE"


ON_DEMAND_LICENSE = LicenseType.ON_DEMAND_LICENSE
ON_DEMAND_FULL_USE_LICENSE = LicenseType.ON_DEMAND_FULL_USE_LICENSE
CUSTOM_LICENSE = LicenseType.CUSTOM_LICENSE
