# generated by datamodel-codegen:
#   filename:  openapi.TollBit.Subdomain.yaml

from __future__ import annotations

from datetime import datetime
from typing import Any, List

from pydantic import BaseModel


class GetContentErrorResponse(BaseModel):
    pass


class PageContent(BaseModel):
    header: str
    body: str
    footer: str


class RateLicensePermission(BaseModel):
    name: str


class RateLicenseResponse(BaseModel):
    licenseType: str
    licensePath: str
    permissions: List[RateLicensePermission]
    validUntil: datetime


class RatePrice(BaseModel):
    priceMicros: int
    currency: str


class ContentRate(BaseModel):
    price: RatePrice
    license: RateLicenseResponse
    error: str


class GetContentResponse(BaseModel):
    content: PageContent
    metadata: Any
    rate: ContentRate
