# generated by datamodel-codegen:
#   filename:  openapi.TollBit.Apis.yaml

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel


class Format(Enum):
    html = 'html'
    markdown = 'markdown'


class CreateSubdomainAccessTokenRequest(BaseModel):
    url: AnyUrl
    userAgent: str
    maxPriceMicros: int
    currency: str
    licenseType: str
    licenseCuid: str
    format: Format


class CreateSubdomainAccessTokenResponse(BaseModel):
    token: str


class Error(BaseModel):
    pass


class Type(Enum):
    http = 'http'


class Scheme(Enum):
    Bearer = 'Bearer'


class SubdomainAccessToken(BaseModel):
    type: Type
    scheme: Scheme
